{% set version = "0.3.1" %}

package:
  name: sciplot
  version: {{ version }}

source:
  url: https://github.com/sciplot/sciplot/archive/v{{ version }}.tar.gz
  sha256: d5f8fa7783920c0db4f54d8d9cea8a5e50be99153e81dcaccf91532994ebbad0

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - python
    - ninja
    - ccache                         # [unix]
    - clcache                        # [win]
    - catch2

test:
  files:
    - test/

  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

about:
  home: https://sciplot.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A modern C++ scientific plotting library powered by gnuplot.
  doc_url: https://sciplot.github.io
  dev_url: https://github.com/sciplot/sciplot

extra:
  recipe-maintainers:
    - allanleal
